apiVersion: v1
kind: Service
metadata:
  name: podname-svc
spec:
  selector:
    app: podname
  ports:
    - name: http
      port: 8080 # svc port
      targetPort: 80 # ep port
      nodePort: 32123 # node port
      protocol: TCP
  type: NodePort
